apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
      - ./infra/k8s-dev/*
build:
  local: 
    push: false
  artifacts:
    - image: weijuzheng/auth
      context: auth
      docker: 
        dockerfile: Dockerfile
      sync:
        manual: 
          - src: 'src/**/*.ts'
            dest: .
    - image: weijuzheng/client
      context: client
      docker: 
        dockerfile: Dockerfile
      sync:
        manual: 
          - src: '**/*.js'
            dest: .
    - image: weijuzheng/tickets
      context: tickets
      docker: 
        dockerfile: Dockerfile
      sync:
        manual: 
          - src: 'src/**/*.ts'
            dest: .
    - image: weijuzheng/orders
      context: orders
      docker: 
        dockerfile: Dockerfile
      sync:
        manual: 
          - src: 'src/**/*.ts'
            dest: .
    - image: weijuzheng/expiration
      context: expiration
      docker: 
        dockerfile: Dockerfile
      sync:
        manual: 
          - src: 'src/**/*.ts'
            dest: .
    - image: weijuzheng/payments
      context: payments
      docker: 
        dockerfile: Dockerfile
      sync:
        manual: 
          - src: 'src/**/*.ts'
            dest: .